                                # This is a comment line

name: Node.js CI                # Name of your workflow
on:                             # When event should be triggered
  push:                         # The name of the GitHub event that triggers the workflow
    branches: [ master ]        # Triggered only when push event occurs on master branch

jobs:                           # Jobs starts from here
  build:                        # First job named "build"

    runs-on: self-hosted        # Commputer where building and testing should be done

    strategy:
      matrix:
        node-version: [17.x]   # node-version for which building and testing should be done

    steps:                     # steps ( in order ) what should be done after what
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
